### ISSUE TITLE
sm 1.11 errors

### ISSUE THREAD

**Issue by UltraSHIM** [GAMMACASE/MomSurfFix#13]
After updating to version 1.11, I have the following errors

L 07/22/2022 - 16:31:22: [SM] Exception reported: Pass flags are only supported for virtual hooks.
L 07/22/2022 - 16:31:22: [SM] Blaming: momsurffix2.smx
L 07/22/2022 - 16:31:22: [SM] Call stack trace:
L 07/22/2022 - 16:31:22: [SM]   [0] DHookAddParam
L 07/22/2022 - 16:31:22: [SM]   [1] Line 159, momsurffix/gamemovement.sp::InitGameMovement
L 07/22/2022 - 16:31:22: [SM]   [2] Line 102, D:\__TEST__OTHER\cstrike\addons\sourcemod\scripting\momsurffix2.sp::OnPluginStart
L 07/22/2022 - 16:31:22: [SM] Unable to load plugin "momsurffix2.smx": Error detected in plugin startup (see error logs)

Is there any solution?

**Comment by GAMMACASE** [comment]
Code wasn't yet adapted to support 1.11 sm and its dhooks. You can try to downgrade dhooks to this release https://github.com/peace-maker/DHooks2/releases/tag/v2.2.0-detours17 and see if it works for you for now.

**Comment by UltraSHIM** [comment]
thank you, now it works fine!

**Comment by GAMMACASE** [comment]
I'd prefer this still be opened, as downgrading is more of a workaround here rather then a solution,

**Comment by fearts** [comment]
Would be cool if this could be updated to work with sm 1.11

**Comment by JoinedSenses** [comment]
> After updating to version 1.11, I have the following errors
> 
> L 07/22/2022 - 16:31:22: [SM] Exception reported: Pass flags are only supported for virtual hooks. L 07/22/2022 - 16:31:22: [SM] Blaming: momsurffix2.smx L 07/22/2022 - 16:31:22: [SM] Call stack trace: L 07/22/2022 - 16:31:22: [SM] [0] DHookAddParam L 07/22/2022 - 16:31:22: [SM] [1] Line 159, momsurffix/gamemovement.sp::InitGameMovement L 07/22/2022 - 16:31:22: [SM] [2] Line 102, D:__TEST__OTHER\cstrike\addons\sourcemod\scripting\momsurffix2.sp::OnPluginStart L 07/22/2022 - 16:31:22: [SM] Unable to load plugin "momsurffix2.smx": Error detected in plugin startup (see error logs)
> 
> Is there any solution?

https://github.com/JoinedSenses/MomSurfFix/commit/8ae6915538d9e155b61388e25c43ae1325da0d9b
