### ISSUE TITLE
 Can't get "sm_pSingleton" address from gamedata. after latest csgo update 

### ISSUE THREAD

**Issue by 8guawong** [GAMMACASE/MomSurfFix#15]
L 10/22/2022 - 16:59:11: [SM] Exception reported: [momsurffix2] Can't get "sm_pSingleton" address from gamedata.
L 10/22/2022 - 16:59:11: [SM] Blaming: momsurffix2.smx
L 10/22/2022 - 16:59:11: [SM] Call stack trace:
L 10/22/2022 - 16:59:11: [SM]   [0] SetFailState
L 10/22/2022 - 16:59:12: [SM]   [1] Line 660, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::SetFailStateCustom
L 10/22/2022 - 16:59:12: [SM]   [2] Line 149, momsurffix/gamemovement.sp::InitGameMovement
L 10/22/2022 - 16:59:12: [SM]   [3] Line 99, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::OnPluginStart
L 10/22/2022 - 16:59:12: [SM] Unable to load plugin "momsurffix2.smx": Error detected in plugin startup (see error logs)

sm 6913 windows

**Comment by GAMMACASE** [comment]
Already have fixed that, currently doing other qol stuff for the future, so the update would be out soon.

**Comment by GAMMACASE** [comment]
New gamedata is in the master branch, simply updating gamedata file would fix your issue, but you can wait for the actual release and update to that a bit later.
