### ISSUE TITLE
CGameMovement::TryPlayerMove error

### ISSUE THREAD

**Issue by TheGunter24** [GAMMACASE/MomSurfFix#17]
hey,
it seems like the gamedata update was not successful for linux 
https://github.com/GAMMACASE/MomSurfFix/commit/d71605aa423a205148f9b4e1cdbb21dfe2520317#diff-a3c49ac944e0de4d601db861785572e1723dc40fc13e58d20c39c892fd389564R360

`[SM] Exception reported: [momsurffix2] Can't find start of the "CGameMovement::TryPlayerMove" function.
L 02/26/2023 - 00:41:48: [SM] Blaming: momsurffix2.smx
L 02/26/2023 - 00:41:48: [SM] Call stack trace:
L 02/26/2023 - 00:41:48: [SM]   [0] SetFailState
L 02/26/2023 - 00:41:48: [SM]   [1] Line 663, momsurffix2.sp::SetFailStateCustom
L 02/26/2023 - 00:41:48: [SM]   [2] Line 199, momsurffix2.sp::SetupASMOptimizations
L 02/26/2023 - 00:41:48: [SM]   [3] Line 105, momsurffix2.sp::OnPluginStart
L 02/26/2023 - 00:41:48: [SM] Unable to load plugin "momsurffix2.smx": Error detected in plugin startup (see error logs)`

running latest dev sm / mm

**Comment by GAMMACASE** [comment]
Assuming that's for CSGO? I don't have any problems running this gamedata on debian, so please, double check that you are running latest gamedata on the server. If it is, then please, provide md5 hash for the ``csgo/bin/server.so`` file that is on your server rn (you can do that [here](https://emn178.github.io/online-tools/md5_checksum.html) or use builtin ``md5sum`` linux command).

**Comment by Nyano1337** [comment]
`SetupASMOptimizations` function doesn't exist in 1.1.5, please upgrade your plugin from the latest release
