### ISSUE TITLE
Error Can't get "g_pMemAlloc" address from gamedata.

### ISSUE THREAD

**Issue by hirowatch** [GAMMACASE/MomSurfFix#18]
L 02/28/2023 - 21:14:51: SourceMod error session started
L 02/28/2023 - 21:14:51: Info (map "de_dust2") (file "/srv/csgo/addons/sourcemod/logs/errors_20230228.log")
L 02/28/2023 - 21:14:51: [SM] Exception reported: [momsurffix2] Can't get "g_pMemAlloc" address from gamedata.
L 02/28/2023 - 21:14:51: [SM] Blaming: fixgame/momsurffix2.smx
L 02/28/2023 - 21:14:51: [SM] Call stack trace:
L 02/28/2023 - 21:14:51: [SM]   [0] SetFailState
L 02/28/2023 - 21:14:51: [SM]   [1] Line 663, C:\SourceMod_1.10_6545\scripting\momsurffix2.sp::SetFailStateCustom
L 02/28/2023 - 21:14:51: [SM]   [2] Line 152, momsurffix/utils.sp::InitUtils
L 02/28/2023 - 21:14:51: [SM]   [3] Line 99, C:\SourceMod_1.10_6545\scripting\momsurffix2.sp::OnPluginStart
L 02/28/2023 - 21:14:51: [SM] Unable to load plugin "fixgame/momsurffix2.smx": Error detected in plugin startup (see error logs)
L 02/28/2023 - 21:14:57: Error log file session closed.

**Comment by GAMMACASE** [comment]
Make sure the gamedata is up to date, and also what game and OS?

**Comment by hirowatch** [comment]
CS:GO, Linux

**Comment by hirowatch** [comment]
what :D

L 03/01/2023 - 23:37:58: [SM] Exception reported: [momsurffix2] Can't find start of the "CGameMovement::TryPlayerMove" function.
L 03/01/2023 - 23:37:58: [SM] Blaming: fixgame/momsurffix2.smx
L 03/01/2023 - 23:37:58: [SM] Call stack trace:
L 03/01/2023 - 23:37:58: [SM]   [0] SetFailState
L 03/01/2023 - 23:37:58: [SM]   [1] Line 663, C:\SourceMod_1.10_6545\scripting\momsurffix2.sp::SetFailStateCustom
L 03/01/2023 - 23:37:58: [SM]   [2] Line 199, C:\SourceMod_1.10_6545\scripting\momsurffix2.sp::SetupASMOptimizations
L 03/01/2023 - 23:37:58: [SM]   [3] Line 105, C:\SourceMod_1.10_6545\scripting\momsurffix2.sp::OnPluginStart
L 03/01/2023 - 23:37:58: [SM] Unable to load plugin "fixgame/momsurffix2.smx": Error detected in plugin startup (see error logs)
L 03/01/2023 - 23:38:04: Error log file session closed.

**Comment by hirowatch** [comment]
compil 1.11?

**Comment by Nyano1337** [comment]
`SetupASMOptimizations` function doesn't exist in 1.1.5, please upgrade your plugin from the latest release

**Comment by hirowatch** [comment]
Thanks, plugin startup
