### ISSUE TITLE
Is this portable to TF2?

### ISSUE THREAD

**Issue by sapphonie** [GAMMACASE/MomSurfFix#2]
Would love to see this used in TF2 surf servers!

**Comment by GAMMACASE** [comment]
I guess it is possible, but never played tf2 and I don't have linux server for it to test it on, and it can vary a lot from windows version, so can't go anywhere until I have everything I need for testings

**Comment by JoinedSenses** [comment]
https://github.com/JoinedSenses/MomSurfFix

**Comment by GAMMACASE** [comment]
Closing this for now.
