### ISSUE TITLE
Crashing on some maps

### ISSUE THREAD

**Issue by Z-RAY-Z** [GAMMACASE/MomSurfFix#3]
I was check Accelerator logs and found some crashes with this plugin in some maps.
Game CS:GO, Metamod:Source 1.11.0-dev+1128. "Momentum surf fix '2" (1.1.1) by GAMMA CASE.
Problematic maps: surf_machine4_go_snf and surf_year3000_dm_csgo
Accelerator Links:
https://crash.limetech.org/vjqsri5c2ywa
https://crash.limetech.org/myy3cznszdpk

**Comment by GAMMACASE** [comment]
Can you tell me where exactly should I go on these maps for crash to happen?

**Comment by Z-RAY-Z** [comment]
I can't tell - i don't see it. But i can provide more info from Throttle.
[crash1.txt](https://github.com/GAMMACASE/MomSurfFix/files/4143185/crash1.txt)
[crash2.txt](https://github.com/GAMMACASE/MomSurfFix/files/4143186/crash2.txt)

**Comment by GAMMACASE** [comment]
Alright I'll play around on these maps, to see if I can recreate these crashes.

**Comment by Z-RAY-Z** [comment]
I forget say that i running server on 102.4 Tick.

**Comment by GAMMACASE** [comment]
I've deployed a fix for your issue, wasn't able to reproduce your crashes but found error in code that is related to your problem, can you please compile from master branch and see if the issue is resolved? Also thanks for the report and detailed info you provided, wouldn't be able to find that bug without that.

**Comment by Z-RAY-Z** [comment]
Thank you for fix, i put fixed version on server and look to crashes for a while.

**Comment by GAMMACASE** [comment]
I guess problem is solved, reopen this issue if you'll met this crash again.
