### ISSUE TITLE
Plugin broken after latest update

### ISSUE THREAD

**Issue by ghost** [GAMMACASE/MomSurfFix#8]
CSGO changed the signature so momsurffix no longer loads 

sm plugins reload momsurffix2
L 11/10/2021 - 01:26:45: [SM] Exception reported: [momsurffix2] Can't get "sm_pSingleton" address from gamedata.
L 11/10/2021 - 01:26:45: [SM] Blaming: momsurffix2.smx
L 11/10/2021 - 01:26:45: [SM] Call stack trace:
L 11/10/2021 - 01:26:45: [SM]   [0] SetFailState
L 11/10/2021 - 01:26:45: [SM]   [1] Line 660, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::SetFailStateCustom
L 11/10/2021 - 01:26:45: [SM]   [2] Line 149, momsurffix/gamemovement.sp::InitGameMovement
L 11/10/2021 - 01:26:45: [SM]   [3] Line 99, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\momsurffix2.sp::OnPluginStart
[SM] Plugin momsurffix2.smx failed to reload: Error detected in plugin startup (see error logs).

**Comment by ghost** [comment]
Thanks to @Ciallo-Ani
Replace line 368 in momsurffix2.games.txt within csgo/addons/sourcemod/gamedata

"linux"            "\x55\x89\xE5\x57\x56\x31\xF6\x53\x81\xEC\x9C\x01\x00\x00\xC7\x85\x2C\xFF\xFF\xFF\x00\x00\x00\x00"

**Comment by GAMMACASE** [comment]
Thanks for the report, latest gamedata file in the release archive (or you can also find it in the master branch).
